# Generated by Django 2.2.2 on 2019-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('companyName', models.CharField(max_length=100)),
                ('joinDate', models.DateField()),
            ],
        ),
    ]
